export const empty_dashboard = {
  title: 'Start Boosting Your Engagement Today!',
  description:
    'Create smart links that open directly in the native apps, driving higher engagement, boosting followers & subscribers, and better user experience.',
  blocks: [
    {
      title: 'Increase Engagement:',
      description:
        'Smart links open directly in the native app, reducing friction and increasing user interaction.',
    },
    {
      title: 'Easy to Use:',
      description: 'Create and manage your links with just a few clicks.',
    },
    {
      title: 'Track Performance:',
      description:
        'Monitor link performance with detailed analytics and insights.',
    },
    {
      title: 'Collaboration:',
      description: 'Collaborate with brand and get rewarding deal.',
    },
  ],
};

export const LinksData = [
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Physic',
    totalClicks: 140,
    percent: 22,
    indicateUp: false,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 140,
    percent: 75,
    indicateUp: true,
  },
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Physic',
    totalClicks: 140,
    percent: 22,
    indicateUp: false,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 140,
    percent: 75,
    indicateUp: true,
  },
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Physic',
    totalClicks: 140,
    percent: 22,
    indicateUp: false,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 140,
    percent: 75,
    indicateUp: true,
  },
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Medicne',
    totalClicks: 170,
    percent: 29,
    indicateUp: false,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 10,
    percent: 23,
    indicateUp: false,
  },
];