export const empty_dashboard = {
  title: 'Start Boosting Your Engagement Today!',
  description:
    'Create smart links that open directly in the native apps, driving higher engagement, boosting followers & subscribers, and better user experience.',
  blocks: [
    {
      title: 'Increase Engagement:',
      description:
        'Smart links open directly in the native app, reducing friction and increasing user interaction.',
    },
    {
      title: 'Easy to Use:',
      description: 'Create and manage your links with just a few clicks.',
    },
    {
      title: 'Track Performance:',
      description:
        'Monitor link performance with detailed analytics and insights.',
    },
    {
      title: 'Collaboration:',
      description: 'Collaborate with brand and get rewarding deal.',
    },
  ],
};

export const LinksData = [
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
    id: 1,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Physic',
    totalClicks: 140,
    percent: 22,
    indicateUp: false,
    id: 2,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 140,
    percent: 75,
    indicateUp: true,
    id: 3,
  },
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
    id: 4,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Physic',
    totalClicks: 140,
    percent: 22,
    indicateUp: false,
    id: 5,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 140,
    percent: 75,
    indicateUp: true,
    id: 6,
  },
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
    id: 7,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Physic',
    totalClicks: 140,
    percent: 22,
    indicateUp: false,
    id: 8,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 140,
    percent: 7,
    indicateUp: true,
    id: 9,
  },
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
    id: 10,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Medicne',
    totalClicks: 170,
    percent: 290,
    indicateUp: false,
    id: 11,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 10,
    percent: 2,
    indicateUp: false,
    id: 12,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Physic',
    totalClicks: 140,
    percent: 22,
    indicateUp: false,
    id: 13,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 140,
    percent: 75,
    indicateUp: true,
    id: 14,
  },
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
    id: 15,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Physic',
    totalClicks: 140,
    percent: 22,
    indicateUp: false,
    id: 16,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 140,
    percent: 7,
    indicateUp: true,
    id: 17,
  },
  {
    logo: '/assets/youtubeLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Youtube',
    tags: '#Educational #Sciences',
    totalClicks: 200,
    percent: 18,
    indicateUp: true,
    id: 18,
  },
  {
    logo: '/assets/amazonLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Amazon',
    tags: '#Educational #Medicne',
    totalClicks: 170,
    percent: 290,
    indicateUp: false,
    id: 19,
  },
  {
    logo: '/assets/spotifyLogo.svg',
    link: 'https://linkfluencerstg.addwebprojects.com/nextdor',
    label: 'Spotify',
    tags: '#Educational #Music',
    totalClicks: 10,
    percent: 2,
    indicateUp: false,
    id: 20,
  },
];

export const UserManagementData = [
  {
    id:'EKG3345543',
    name:'Cameron Williamson',
    email:'harrystyls123@gmail.com',
    role:'users',
    date:'15 Dec, 2024',
    invitedBy:'cameron Williamson',
  },
  {
    id:'EKG3345543',
    name:'Cameron Williamson',
    email:'harrystyls123@gmail.com',
    role:'users',
    date:'15 Dec, 2024',
    invitedBy:'cameron Williamson',
  },{
    id:'EKG3345543',
    name:'Cameron Williamson',
    email:'harrystyls123@gmail.com',
    role:'users',
    date:'15 Dec, 2024',
    invitedBy:'cameron Williamson',
  },{
    id:'EKG3345543',
    name:'Cameron Williamson',
    email:'harrystyls123@gmail.com',
    role:'users',
    date:'15 Dec, 2024',
    invitedBy:'cameron Williamson',
  },
]
export const walletData = [
  {
    id:'EKG3345543',
    invoiceDate:'10, Dec, 2021',
    datePaid:'10, Dec, 2021',
    status:'pending',
    paymentMode:'398********723 (Visa)',
    amount:'$129 USD',
  },
  {
    id:'EKG3345543',
    invoiceDate:'10, Dec, 2021',
    datePaid:'10, Dec, 2021',
    status:'failed',
    paymentMode:'398********723 (Visa)',
    amount:'$129 USD',
  },
  {
    id:'EKG3345543',
    invoiceDate:'10, Dec, 2021',
    datePaid:'10, Dec, 2021',
    status:'success',
    paymentMode:'398********723 (Visa)',
    amount:'$129 USD',
  },
]